spring:
  application:
    name: eureka

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    register-with-eureka: false
    fetch-registry: false