spring:
  data:
    mongodb:
      host: 192.168.0.110
      port: 27017
      password: 1234qwer
      username: root
      database: market

springdoc:
  api-docs:
    # http://localhost:8081/product/api - тут будут endpoints в формате json
    path: /product/api
  swagger-ui:
    # http://localhost:8081/product/swagger-ui/index.html - здесь будет swagger ui
    path: /product

server:
  port: 8081

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8083/eureka/