server:
  port: 8082


spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/dimik/IdeaProjects/MARKET/configs
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8083/eureka/